### ISSUE TITLE
Not able to execute 'go build'

### ISSUE THREAD

**Issue by pipinstallyogi** [ulranh/sapnwrfc_exporter#1]
Hallo everyone,

I am using the go version 'go version go1.13' on SUSE Linux 12.3.
I have done everything correctly to configure the exporter (SAP library in /usr/sap folder as mentioned, giving the path etc.) but when I run the command 'go build', I get the following error:
...
go build github.com/sap/gorfc/gorfc: invalid flag in #cgo CFLAGS: -minline-all-stringops
....
Any Inputs what the reason might be and how to solve this?
Any help is highly appreciated

**Comment by ulranh** [comment]
Do you have the following environment variables set?

export SAPNWRFC_HOME=/usr/sap/nwrfcsdk
export CGO_CFLAGS="-I $SAPNWRFC_HOME/include"
export CGO_LDFLAGS="-L $SAPNWRFC_HOME/lib"
export CGO_CFLAGS_ALLOW="^.*"
export CGO_LDFLAGS_ALLOW="^.*"

**Comment by pipinstallyogi** [comment]
I have these one set in environment variable:

PATH=$PATH:/usr/local/go/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/sap/nwrfcsdk/lib
CGO_LDFLAGS="-L /usr/sap/nwrfcsdk/lib"
CGO_CFLAGS="-I /usr/sap/nwrfcsdk/include"
CGO_LDFLAGS_ALLOW=^.*
CGO_CFLAGS_ALLOW=^.*


As you have mentioned, I have added them in the way you have written :

export SAPNWRFC_HOME=/usr/sap/nwrfcsdk
export CGO_CFLAGS="-I $SAPNWRFC_HOME/include"
export CGO_LDFLAGS="-L $SAPNWRFC_HOME/lib"
export CGO_CFLAGS_ALLOW="^."
export CGO_LDFLAGS_ALLOW="^."


Now while running 'go build' I am facing with following error:

runtime/cgo
exec: "gcc": executable file not found in $PATH

Seems like the error now belongs to the GCC compiler. I am trying onto that. If you believe it is something else kindly provide the inputs.
Thanks

**Comment by ulranh** [comment]
Yes, the gcc  compiler is a prerequisite for the [gorfc](https://github.com/SAP/gorfc) package.

**Comment by pipinstallyogi** [comment]
Thanks for the help. Will Look into the issue by installing gcc now.
