### ISSUE TITLE
Number of Active USers in SAP System/ Number of cancelled jobs

### ISSUE THREAD

**Issue by pipinstallyogi** [ulranh/sapnwrfc_exporter#3]
Hello Everyone,

Can we also find out the SAP System statistics such as "Number of Active users" and "Number of cancelled/Running Jobs" using this exporter? What should be the entries in configuration file? Please provide some inputs. Thanks in advance.

Best

**Comment by ulranh** [comment]
If you take a look at the example directories of this and the hana_sql_exporter, you will find the answer to these questions.

**Comment by pipinstallyogi** [comment]
Thanks a lot. Got the examples.
