### ISSUE TITLE
Could you please release a new version?

### ISSUE THREAD

**Issue by AyaSenri** [ulranh/sapnwrfc_exporter#4]
I encounter an issue when I use v0.1. When I run web , it raises error like this:

[root@localhost nwrfc_exporter]# ./sapnwrfc_exporter web -port 9773 -config ./error_test.toml 
time="25-09-2020 09:58:42" level=error msg="Can't find password for system" system=BHB

However, when I use code from branch master, running web will work.
Many commits submit after v0.1, I think v0.1 might be too old. Could you please release a new version?

**Comment by ulranh** [comment]
The master branch should be o.k. at the moment and you can use it. But no problem, I will release a new version in the next time.

Regarding the  v0.1 version I tried the following and it worked for me:
1. Create config file sapnwrfc.toml with following entries:
```
[[Systems]]
  Name = "s01"
  Usage = "development"
  Tags = ["erp"]
  User = "user1"
  Lang = "en"
  Client = "100"
  Server = "system01.domain"
  Sysnr = "01"

[[TableMetrics]]
  Name = "sap_users"
  Help = "sm04 help"
  MetricType = "gauge"
  TagFilter = ["erp"]
  FuMo = "TH_USER_LIST"
  Table = "USRLIST"
  AllServers = true
  [TableMetrics.Params]
  [TableMetrics.RowCount]
    guiversion = ["76", "75", "74"]
    mandt = ["000", "090", "100", "400"]
    type = [4]
  [TableMetrics.RowFilter]

```
2. add password:

`$ ./sapnwrfc_exporter pw -system s01 -config ./sapnwrfc.toml`

3. start exporter_

`$ ./sapnwrfc_exporter web -config ./sapnwrfc.toml`

4. run `http://localhost:9663/metrics` in the browser

**Comment by AyaSenri** [comment]
Thanks a lot.
