### ISSUE TITLE
Field metrics error

### ISSUE THREAD

**Issue by ChernykhAN** [ulranh/sapnwrfc_exporter#7]
I'm getting error with field metric

```
time="28-10-2020 19:00:02" level=error msg="getRfcData: len(labels) != len(labelValues)" server=chq system=chq
```

configuration 
```
[[FieldMetrics]]
  Name = "sap_kernel_info"
  Help = "SAP kernel and db client info"
  MetricType = "gauge"
  TagFilter = []
  AllServers = true
  FunctionModule = "TH_SAPREL2"
  fieldLabels = ["kern_rel", "kern_dblib", "kern_patchlevel"]
```

**Comment by ulranh** [comment]
I adapted the error message for that case. In my view one or more of the fieldLabels in ["kern_rel", "kern_dblib", "kern_patchlevel"] is no valid export parameter of your version of function module TH_SAPREL2 perhaps due to the logon language.
